[package]
name = "winereg"
version = "0.1.0"
edition = "2024"

[lib]
name = "winereg"

[dependencies]
anyhow = "1.0"
once_cell = "1.19"
regex = "1.11"
thiserror = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
